#!/bin/sh

ELASTICSEARCH_SERVICE_NAME=$(echo "${ELASTICSEARCH_SERVICE_NAME:-ELASTICSEARCH}" | awk '{print toupper($0)}')
SVC_HOST=${ELASTICSEARCH_SERVICE_NAME}_SERVICE_HOST
SVC_PORT=${ELASTICSEARCH_SERVICE_NAME}_SERVICE_PORT
ELASTICSEARCH_URL=$(eval echo \$${SVC_HOST}):$(eval echo \$${SVC_PORT})

if [ "${ELASTICSEARCH_URL}" == ":" ]; then
  >&2 echo "Invalid Elasticsearch URL"
  exit 1
fi

mkdir /etc/fluent

cat << 'EOF' > /etc/fluent/fluent.conf
<source>
  type tail
  path /var/lib/docker/containers/*/*-json.log
  pos_file /etc/fluent/fluentd-docker.pos
  time_format %Y-%m-%dT%H:%M:%S
  tag docker.*
  format json
</source>

<match docker.var.lib.docker.containers.*.*.log>
  type kubernetes
  container_id ${tag_parts[5]}
  tag docker.${name}
</match>

<match kubernetes>
  type elasticsearch
  logstash_format true
  reload_connections false
EOF

cat << EOF >> /etc/fluent/fluent.conf
  hosts ${ELASTICSEARCH_URL}
EOF

cat << 'EOF' >> /etc/fluent/fluent.conf
</match>
EOF

exec fluentd
